name: online_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^12.4.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_bloc: ^9.0.0
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  flutter_stripe: ^11.4.0
  flutter_lints: ^5.0.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.2.0+3
  share_plus: ^7.0.0  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5 
  build_runner: ^2.4.8  
